Fix verify-boilerplate target (#25803)
* boilerplate: print out how many files were verified

So that we can know whether this script actually did anything.

* boilerplate: make some adjustments to work in this repo

* boilerplate: resync with repo-infra

Back out changes that were made after importing this from repo-infra,
because the original version seems to work fine.

* boilerplate: fix test failure

The additional newlines in the boilerplate was causing:

======================================================================
FAIL: test_boilerplate (__main__.TestBoilerplate)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/markmc/git/kubernetes/test-infra/./hack/boilerplate/verify_boilerplate_test.py", line 58, in test_boilerplate
    self.assertEqual(output, expected)
AssertionError: '3 files have incorrect boilerplate headers:\nfail.go\nfail.py\npass.py\n' != '2 files have incorrect boilerplate headers:\nfail.go\nfail.py\n'
- 3 files have incorrect boilerplate headers:
? ^
+ 2 files have incorrect boilerplate headers:
? ^
  fail.go
  fail.py
- pass.py

* boilerplate: fix pylint warnings

Address these warnings with pragma controls rather than hacking
copied-and-pasted code.

  hack/boilerplate/verify_boilerplate.py:129:12: W0612: Unused variable 'i' (unused-variable)
  hack/boilerplate/verify_boilerplate.py:87:0: R0911: Too many return statements (8/6) (too-many-return-statements)
  hack/boilerplate/verify_boilerplate.py:87:0: R0912: Too many branches (15/12) (too-many-branches)

* gerrit: add boilerplate