prow/gcsupload: Set Content-Type and Content-Encoding
Content-Type is recommended [1].  And from [1]:

> If you do not specify a content type, Cloud Storage defaults to
> [`application/octet-stream`](https://tools.ietf.org/html/rfc2046#section-4.5.1)
> when it serves the object.

although there seems to be some (minimal) autodetection in place at the moment:

  $ curl -sI https://storage.googleapis.com/origin-ci-test/logs/release-openshift-origin-installer-e2e-aws-4.1/317/build-log.txt | grep Content
  Content-Type: text/plain; charset=utf-8
  Content-Length: 2175
  $ curl -sI https://storage.googleapis.com/origin-ci-test/logs/release-openshift-origin-installer-e2e-aws-4.1/317/finished.json | grep Content
  Content-Type: text/plain; charset=utf-8
  Content-Length: 226
  $ curl -sI https://storage.googleapis.com/origin-ci-test/logs/release-openshift-origin-installer-e2e-aws-4.1/317/artifacts/junit_operator.xml | grep Content
  Content-Type: text/plain; charset=utf-8
  Content-Length: 672
  $ curl -sI https://storage.googleapis.com/origin-ci-test/logs/release-openshift-origin-installer-e2e-aws-4.1/317/artifacts/e2e-aws/openapi.json.gz | grep Content
  Content-Type: application/x-gzip
  Content-Length: 278997

With this change, clients will get better Content-Type
(e.g. application/json instead of text/plain), and .gz and .gzip
extensions are being shifted out of Content-Type and into
Content-Encoding.  That will allow clients to opt-in to over-the-wire
compression, via Accept-Encoding headers (on the client side) and
decompressive transcoding (on the server side [2]).

In support of this change, I've added a new FileUploadWithMetadata.
I've also removed some redundant code from DataUpload and made that
function just syntactic sugar for DataUploadWithMetadata to DRY things
up a bit.

Also interesting, TypeByExtension's docs say [3]:

> The built-in table is small but on unix it is augmented by the local
> system's mime.types file(s) if available under one or more of these
> names:
>
> /etc/mime.types
> /etc/apache2/mime.types
> /etc/apache/mime.types
>
> On Windows, MIME types are extracted from the registry.
>
> Text types have the charset parameter set to "utf-8" by default.

So the current implementation is somewhat host-dependent for type
detection.  In fact, the AddExtensionType in metadata_test.go is
because the test-infra CI container lacks an /etc/mime.types entry for
the 'log' extension [4]:

  --- FAIL: TestMetadataFromFileName (0.02s)
      --- FAIL: TestMetadataFromFileName/log (0.00s)
          metadata_test.go:129: expected metadata map[string]string{"Content-Type":"text/plain; charset=utf-8"} but got map[string]string{}

If assuming UTF-8 is considered too risky,
DetectContentType [5] uses peak-inside magic, which presumably
includes detecting charsets.

One potential downside is that, now that compression is part of the
encoding negotiation, it's not a fundamental part of the resource, so
I've removed it from uploaded filenames.  Scripts and users who are
used to finding whatever.txt.gz will now want to request whatever.txt
with 'Accept-Encoding: gzip'.  But copying the content up twice to
provide a gentler transition seemed wasteful of GCS storage space.  We
could add a new flag to allow callers to opt-in to a graceful
transition (--gzip-copies?), but I'm punting on that until we have a
demonstrated use-case where my current hard cut-over will be too
painful.

Bazel update is via:

  $ hack/update-bazel.sh

[1]: https://cloud.google.com/storage/docs/xml-api/put-object#request-headers
[2]: https://cloud.google.com/storage/docs/transcoding
[3]: https://golang.org/pkg/mime/#TypeByExtension
[4]: https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/test-infra/12391/pull-test-infra-bazel/1122571776325324800/build-log.txt
[5]: https://golang.org/pkg/net/http/#DetectContentType