deps(hack/tools): bump github.com/docker/docker to v27
```console
$ go get -u github.com/docker/docker@v27
go: upgraded github.com/docker/docker v24.0.6+incompatible => v27.5.1+incompatible
```

Cannot go to current latest v28 because `ko` fails to build:

```console
$ make build-images
hack/make-rules/go-run/arbitrary.sh run ./hack/prowimagebuilder --prow-images-file=./.prow-images.yaml --ko-docker-repo="ko.local" --push=false
+ go run ./hack/prowimagebuilder --prow-images-file=./.prow-images.yaml --ko-docker-repo=ko.local --push=false
INFO[0000] /home/afri/Projects/RH/kubernetes-sigs/prow   cmd="[git rev-parse --show-toplevel]"
ERRO[0000] # github.com/google/go-containerregistry/pkg/v1/daemon
../../../../go/pkg/mod/github.com/google/go-containerregistry@v0.16.1/pkg/v1/daemon/options.go:40:9: cannot use client.NewClientWithOpts(client.FromEnv) (value of type *client.Client) as Client value in return statement: *client.Client does not implement Client (wrong type for method ImageHistory)
		have ImageHistory(context.Context, string, ...client.ImageHistoryOption) ([]image.HistoryResponseItem, error)
		want ImageHistory(context.Context, string) ([]image.HistoryResponseItem, error)
../../../../go/pkg/mod/github.com/google/go-containerregistry@v0.16.1/pkg/v1/daemon/options.go:101:53: undefined: types.ImageLoadResponse  args="[build -o /home/afri/Projects/RH/kubernetes-sigs/prow/_bin/ko github.com/google/ko]" cmd=go
ERRO[0000] Failed ensure ko                              error="exit status 1"
```

xref: https://github.com/ko-build/ko/pull/1494